"""initial schema

Revision ID: 3c0a0b736b45
Revises: 
Create Date: 2026-03-03 22:58:27.503456

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0a0b736b45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bikes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('captain_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('ride_date', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('estimated_end_time', sa.String(length=10), nullable=True),
    sa.Column('difficulty_level', sa.Enum('easy', 'moderate', 'hard', 'expert', name='difficultylevel'), nullable=True),
    sa.Column('recommended_bike_type', sa.String(length=100), nullable=True),
    sa.Column('break_schedule', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'completed', 'cancelled', name='ridestatus'), nullable=True),
    sa.Column('max_riders', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    op.create_table('ride_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'left', name='participantstatus'), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_break_stop', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride_stops')
    op.drop_table('ride_participants')
    op.drop_table('chat_groups')
    op.drop_table('rides')
    op.drop_table('bikes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
