"""activity tracking, gear, clubs, events, hazards, trips, comments

Revision ID: a7970339e50c
Revises: d3ca57bde9d5
Create Date: 2026-08-26 19:30:17.517015

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7970339e50c'
down_revision: Union[str, None] = 'd3ca57bde9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # autogenerate doesn't emit CREATE TYPE for a new enum used only in
    # add_column (only when it appears in a fresh create_table) - do it
    # explicitly before badges.rarity references it below.
    badge_rarity = postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='badge_rarity')
    badge_rarity.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ride_log_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_log_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_log_id'], ['ride_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'slug', name='uq_club_badge_slug')
    )
    op.create_table('club_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='club_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_membership')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_point', sa.String(length=255), nullable=True),
    sa.Column('meeting_latitude', sa.Float(), nullable=True),
    sa.Column('meeting_longitude', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hazard_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('hazard_type', sa.Enum('pothole', 'gravel', 'police_check', 'animal_crossing', 'accident', 'waterlogging', 'other', name='hazard_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_ride_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('ride_log_id', sa.UUID(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ride_log_id'], ['ride_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'ride_log_id', name='uq_trip_ride_log')
    )
    op.create_table('club_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('goal_km', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reward_club_badge_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_club_badge_id'], ['club_badges.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_rsvps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('going', 'interested', name='rsvp_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_rsvp')
    )
    op.create_table('user_club_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('club_badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_badge_id'], ['club_badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'club_badge_id', name='uq_user_club_badge')
    )
    op.add_column('badges', sa.Column('rarity', postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='badge_rarity', create_type=False), server_default='common', nullable=False))
    # server_default (not just the ORM-level default) on these three -
    # existing bike rows need a real value at ALTER time, not just for
    # future inserts.
    op.add_column('bikes', sa.Column('total_km_since_service', sa.Float(), nullable=False, server_default='0'))
    op.add_column('bikes', sa.Column('total_km_lifetime', sa.Float(), nullable=False, server_default='0'))
    op.add_column('bikes', sa.Column('service_interval_km', sa.Integer(), nullable=False, server_default='3000'))
    op.add_column('bikes', sa.Column('last_serviced_at', sa.DateTime(timezone=True), nullable=True))
    # Note: autogenerate also proposed dropping several indexes on
    # post_comments/posts/reports/user_badges - pre-existing drift between
    # an earlier migration and the current models, unrelated to this
    # migration's actual purpose. Left alone rather than touched as a
    # side effect (same call made in d3ca57bde9d5).
    op.add_column('ride_logs', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('ride_logs', sa.Column('moving_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('ride_logs', sa.Column('avg_speed_kmh', sa.Float(), nullable=True))
    op.add_column('ride_logs', sa.Column('elevation_gain_m', sa.Float(), nullable=True))
    op.add_column('ride_logs', sa.Column('terrain_type', sa.String(length=20), nullable=True))
    op.add_column('ride_logs', sa.Column('relative_effort', sa.Integer(), nullable=True))
    op.add_column('ride_logs', sa.Column('matched_route_id', sa.UUID(), nullable=True))
    op.add_column('ride_logs', sa.Column('recorded_track', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'ride_logs', 'routes', ['matched_route_id'], ['id'], ondelete='SET NULL')
    op.add_column('ride_media', sa.Column('captured_latitude', sa.Float(), nullable=True))
    op.add_column('ride_media', sa.Column('captured_longitude', sa.Float(), nullable=True))
    op.add_column('ride_media', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('routes', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('routes', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('source_ride_log_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'routes', 'ride_logs', ['source_ride_log_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_verified_rider', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('privacy_zone_radius_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_zone_radius_km')
    op.drop_column('users', 'is_verified_rider')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'source_ride_log_id')
    op.drop_column('routes', 'distance_km')
    op.drop_column('routes', 'is_published')
    op.drop_column('ride_media', 'captured_at')
    op.drop_column('ride_media', 'captured_longitude')
    op.drop_column('ride_media', 'captured_latitude')
    op.drop_constraint(None, 'ride_logs', type_='foreignkey')
    op.drop_column('ride_logs', 'recorded_track')
    op.drop_column('ride_logs', 'matched_route_id')
    op.drop_column('ride_logs', 'relative_effort')
    op.drop_column('ride_logs', 'terrain_type')
    op.drop_column('ride_logs', 'elevation_gain_m')
    op.drop_column('ride_logs', 'avg_speed_kmh')
    op.drop_column('ride_logs', 'moving_duration_seconds')
    op.drop_column('ride_logs', 'distance_km')
    op.drop_column('bikes', 'last_serviced_at')
    op.drop_column('bikes', 'service_interval_km')
    op.drop_column('bikes', 'total_km_lifetime')
    op.drop_column('bikes', 'total_km_since_service')
    op.drop_column('badges', 'rarity')
    op.drop_table('user_club_badges')
    op.drop_table('event_rsvps')
    op.drop_table('club_challenges')
    op.drop_table('trip_ride_logs')
    op.drop_table('hazard_reports')
    op.drop_table('events')
    op.drop_table('club_memberships')
    op.drop_table('club_badges')
    op.drop_table('trips')
    op.drop_table('ride_log_comments')
    op.drop_table('clubs')
    # ### end Alembic commands ###
    postgresql.ENUM(name='badge_rarity').drop(op.get_bind())
