"""direct messages

Revision ID: d3ca57bde9d5
Revises: 11069db07490
Create Date: 2026-08-26 19:03:35.634457

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ca57bde9d5'
down_revision: Union[str, None] = '11069db07490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_a_id', sa.UUID(), nullable=False),
    sa.Column('user_b_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_a_id != user_b_id', name='ck_dm_thread_not_self'),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_dm_thread_pair')
    )
    op.create_index('idx_dm_threads_user_a', 'dm_threads', ['user_a_id'], unique=False)
    op.create_index('idx_dm_threads_user_b', 'dm_threads', ['user_b_id'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['dm_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_direct_messages_thread_time', 'direct_messages', ['thread_id', 'created_at'], unique=False)
    # Note: autogenerate also proposed dropping several indexes on
    # post_comments/posts/reports/user_badges - that's pre-existing drift
    # between an earlier migration and the current models, unrelated to
    # direct messages. Left alone here rather than touched as a side effect.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_direct_messages_thread_time', table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index('idx_dm_threads_user_b', table_name='dm_threads')
    op.drop_index('idx_dm_threads_user_a', table_name='dm_threads')
    op.drop_table('dm_threads')
    # ### end Alembic commands ###
